steps:
  - label: ':docker: Build base image'
    command: .buildkite/bin/build

  - wait:
    if: build.env("SCHEDULED_UPDATE") == "true"

  - label: Notify Slack
    command: .buildkite/bin/slack-notify
    if: build.env("SCHEDULED_UPDATE") == "true"

  - wait

  - label: ':docker: Build image awscli'
    command: .buildkite/bin/build
    env:
      IMAGE_VARIANT: awscli

  - wait:
    if: build.branch == "master" && build.author.name == "renovate-bot"

  - block:
    if: build.branch == "master" && build.author.name != "renovate-bot"

  - label: ':docker: Tag latest'
    command: .buildkite/bin/release
    branches: master

  - label: ':docker: Tag awscli'
    command: .buildkite/bin/release
    env:
      IMAGE_VARIANT: awscli
    branches: master