steps:
  - label: ':docker: Build base image'
    command: .buildkite/bin/build

  - wait:
    if: build.env("SCHEDULED_UPDATE") == "true"

  - label: Notify Slack
    command: .buildkite/bin/slack-notify
    if: build.env("SCHEDULED_UPDATE") == "true"

  - wait

  - label: ':docker: Build image awscli'
    command: .buildkite/bin/build
    env:
      IMAGE_VARIANT: awscli

  - label: ':docker: Build image infracost'
    command: .buildkite/bin/build
    env:
      IMAGE_VARIANT: infracost

  - block:
    branches: master

  - label: ':docker: Tag latest'
    command: .buildkite/bin/release
    branches: master